### ISSUE TITLE
Set discovery plugins in configuration

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick-md#5]
To speed up a Statick run when using the configurations provided by md-config.yaml it would help to explicitly list the discovery plugins to use. For example, the md level could be

```
levels:
  web:
    discovery:
      markdown:
        flags: ""
    tool:
      markdownlint:
        flags: ""
```

Similarly, the md_with_pylint level could add python to the discovery plugins enabled.
